[tox]
# Tell Tox to run three separate jobs in this exact order:
envlist = py314, smoke
isolated_build = True

# ==========================================
# JOB 1 & 2: The Python Version Tests
# (Runs automatically for py312 and py313)
# ==========================================
[testenv]
description = "Run normal unit tests to prove Python 3.14 compatibility"
deps = pytest
commands =
    pytest tests/


[testenv:smoke]
description = "Verify the built .whl file installs correctly from the outside"
deps = pytest
changedir = {envtmpdir}
commands =
    pytest {toxinidir}/smoke_tests/
