[tox]
envlist = py312, py313, py314, smoke
isolated_build = True

[testenv]
description = "Run normal unit tests across multiple Python versions"
extras =
    babel
deps =
    hypothesis
    pytest
commands =
    pytest tests/

[testenv:smoke]
description = "Verify the built .whl file installs correctly from the outside"
deps =
    pytest
changedir = {envtmpdir}
commands =
    pytest {toxinidir}/smoke_tests/
